apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jadwal-infara-claim
  namespace: jadwal
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
