apiVersion: v1
kind: PersistentVolume
metadata:
  name: jadwal-infra-volume
  namespace: jadwal
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/jadwal-infra"
